In [1]:
import numpy as np
import random
import matplotlib.pyplot as plt

In [2]:
def energystate(N):
    # generates energy for each site
    state = np.random.uniform(-1, 1, (N,N))
    return state

In [3]:
# Temperature
T = 300
# Boltzmann constant
kB = 8.617332e-5
kT = kB * T

# sites given by N*N
N = 4

config = energystate(N)
config


array([[ 0.94479156,  0.08745995, -0.37674671, -0.19489638],
       [-0.36126966, -0.05172237, -0.99255047,  0.42221828],
       [ 0.06363406, -0.48087055,  0.89374941, -0.49942069],
       [ 0.40075873,  0.90433931, -0.87621448, -0.19430646]])

In [4]:
# generate lattice sites
sites = np.zeros((N,N))

# random point for atom position
a = np.random.randint(0,N)
b = np.random.randint(0,N)

# position of atom set to 1
sites[a, b] = 1
print(sites)

# energy at atom position
s = config[a, b]
print(s)




[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 1.]]
-0.19430646315447686


In [5]:
# set number of hops
n_hops = 3

for n in range(n_hops):
    # set lattice sites to original configuration
    sites[a,b] = 0
    
    # four adjacent sites to atom position
    p1 = config[(a+1)%N,b] 
    p2 = config[a,(b+1)%N]
    p3 = config[(a-1)%N,b]
    p4 = config[a,(b-1)%N]
    
    # energy difference between adjacent sites and position where atom is placed
    dE = np.array([p1-s, p2-s, p3-s, p4-s])
    # rate of hopping, v = 1*exp(-dE/kT)
    v =  np.exp(-dE/kT)
    # generate random number
    Randnum = random.uniform(0,1)
    # set position of pointer
    rk = Randnum * np.sum(v)
    # cumulative sum of energy for four different points, from p1 to p4
    k = np.cumsum(v)

    # going through k1, k1+k2...., ktotal
    check = []
    for i in np.nditer(k):
    # if value smaller than pointer, append to check
        if i < rk:
            check.append(i)
    print(check)

    if len(check) == 0:
        s = p1
    elif len(check) == 1:
        s = p2
    elif len(check) == 2:
        s = p3
    else:
        s = p4
    print(s)
    a,b = np.where(config==s)
    sites[a, b] = 1
    print(sites)
    




[array(1.02308118), array(1.02308118), array(133566.49270836)]
-0.8762144839959731
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]]
[]
[-0.37674671]
[[0. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[]
[-0.99255047]
[[0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
